leads/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('api/lead/', views.LeadListCreate.as_view()),
    path('api/news/', views.NewsCreate.as_view()),
    path('test/image', views.test_image)

]

react_django/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('leads.urls')),
                  path('', include('sport.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

sport/urls.py
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.urls import path, include

from react_django import settings
from sport.views import *
from . import views

app_name = "sport"
urlpatterns = [
    # general

    path('', recent_general_news_games, name='home'),
    path('<int:news_id>/news-detail', news_detail_view, name='news-detail'),

    path('accounts/', include('django.contrib.auth.urls')),  # new
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('reset/', reset_request, name='password_reset'),
    path('<str:hashcode>/reset/', reset, name='password_reset_confirm'),
    path('<str:hashcode>/activate/', activate, name='activate'),

    # football

    path('football/teams', football_teams, name='football_teams'),
    path('<int:team_id>/football/team-detail', football_team_detail_view, name='football-team-detail'),
    path('<int:player_id>/football/player-detail', football_player_detail_view, name='football-player-detail'),
    path('<int:game_id>/football/game-detail', football_game_detail_view, name='football-game-detail'),
    path('football/leagues', football_leagues, name='football_leagues'),
    path('<int:league_id>/football/league_detail', football_league_detail, name='league_detail_football'),

    # basketball

    path('basketball/teams', basketball_teams, name='basketball_teams'),
    path('<int:team_id>/basketball/team-detail', basketball_team_detail_view, name='basketball-team-detail'),
    path('<int:player_id>/basketball/player-detail', basketball_player_detail_view, name='basketball-player-detail'),
    path('<int:game_id>/basketball/game-detail', basketball_game_detail_view, name='basketball-game-detail'),
    path('basketball/leagues', basketball_leagues, name='basketball_leagues'),
    path('<int:league_id>/basketball/league_detail', basketball_league_detail, name='league_detail_basketball'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sport/models/basketball_models.py
from django.contrib.auth.models import User
from django.db import models

from sport.models.football_models import TEAM_SITUATION_IN_GAME
from sport.models.abstract_models import Game, Human, Event, Player, Team, League, Image, Video
from django.utils.translation import ugettext_lazy as _

BASKETBALL_PLAYER_EVENT_CHOICES = (
    ('2PT', 'پرتاب دو امتیازی'),
    ('3PT', 'پرتاب سه امتیازی'),
    ('E', 'خطا'),
    ('R', 'ریباند'),
    ('P', 'پنالتی'),
    ('LP', 'از دست دادن پنالتی'),
    ('CH', 'تعویض'),
)

BASKETBALL_POST_CHOICES = (
    ('G', 'گارد'),
    ('C', 'مرکز'),
    ('GF', 'گارد فوروارد'),
    ('FG', 'فوروارد گارد'),
    ('FC', 'فوروارد سنتر'),
)

BASKETBALL_NON_PLAYER_POST_CHOICES = (
    ('C', 'مربی'),
    ('CH', 'کمک مربی'),
)


class BasketballTeam(Team):
    followers = models.ManyToManyField(User, blank=True, null=True)

    class Meta:
        verbose_name = _('تیم بسکتبال')
        verbose_name_plural = _('تیم های بسکتبال')


class BasketballLeague(League):
    class Meta:
        verbose_name = _('لیگ بسکتبال')
        verbose_name_plural = _('لیگ های بسکتبال')


class BasketballGame(Game):
    league = models.ForeignKey(BasketballLeague, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = _('بازی بسکتبال')
        verbose_name_plural = _('بازی های بسکتبال')


class BasketballPlayer(Player):
    team = models.ForeignKey(BasketballTeam, on_delete=models.CASCADE)
    post = models.CharField(max_length=2, choices=BASKETBALL_POST_CHOICES)

    class Meta:
        verbose_name = _('بسکتبالیست')
        verbose_name_plural = _('بسکتبالیست ها')


class BasketballEvent(Event):
    game = models.ForeignKey(BasketballGame, on_delete=models.CASCADE)  # ?
    event_type = models.CharField(max_length=3, choices=BASKETBALL_PLAYER_EVENT_CHOICES)
    doer = models.ForeignKey(BasketballPlayer, on_delete=models.CASCADE)  # ?

    def __str__(self):
        s = self.doer.first_name + " " + self.doer.last_name + " در بازی " + str(
            self.game.date) + "انجام داد" + self.event_type
        return s

    class Meta:
        verbose_name = _('اتفاق بسکتبالی')
        verbose_name_plural = _('اتفاقات بسکتبالی')


class BasketballNonPlayer(Human):
    team = models.ForeignKey(BasketballTeam, on_delete=models.CASCADE)
    post = models.CharField(max_length=2, choices=BASKETBALL_NON_PLAYER_POST_CHOICES)

    class Meta:
        verbose_name = _('پشتیبان بسکتبالی')
        verbose_name_plural = _('پشتیبان های بسکتبالی')


class BasketballTeamInBasketballGame(models.Model):
    game = models.ForeignKey(BasketballGame, on_delete=models.CASCADE)
    team = models.ForeignKey(BasketballTeam, on_delete=models.CASCADE)

    team_score_Q1 = models.IntegerField(blank=True, null=True)
    team_score_Q2 = models.IntegerField(blank=True, null=True)
    team_score_Q3 = models.IntegerField(blank=True, null=True)
    team_score_Q4 = models.IntegerField(blank=True, null=True)

    property_percent = models.IntegerField(blank=True, null=True)
    situation = models.CharField(max_length=3, choices=TEAM_SITUATION_IN_GAME, blank=True, null=True)
    best_player = models.ForeignKey(BasketballPlayer, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = _('حضور یک تیم بسکتبال در بازی بسکتبال')
        verbose_name_plural = _('حضورهای یک تیم بسکتبال در بازی بسکتبال')

    def __str__(self):
        s = self.team.name + " در بازی " + str(self.game.date)
        return s


class BasketballPlayerInBasketballGame(models.Model):
    game = models.ForeignKey(BasketballGame, on_delete=models.CASCADE)
    player = models.ForeignKey(BasketballPlayer, on_delete=models.CASCADE)
    main_player = models.BooleanField(blank=True, null=True)
    time_of_change = models.TimeField(blank=True, null=True)

    class Meta:
        verbose_name = _('حضور یک بسکتبالیست در بازی بسکتبال')
        verbose_name_plural = _('حضورهای یک بسکتبالیست در بازی بسکتبال')

    def __str__(self):
        s = self.player.first_name + "  " + self.player.last_name
        " در بازی " + str(self.game.date)
        return s


class BasketballImage(Image):
    game = models.ForeignKey(BasketballGame, on_delete=models.CASCADE, blank=True, null=True)
    team = models.ForeignKey(BasketballTeam, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = _('تصویر مرتبط با بسکتبال')
        verbose_name_plural = _('تصاویر مرتبط با بسکتبال')


class BasketballVideo(Video):
    game = models.ForeignKey(BasketballGame, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = _('فیلم مرتبط با بسکتبال')
        verbose_name_plural = _('فیلم های مرتبط با بسکتبال')

sport/views/basketball_views.py
import pandas as pd

from sport.models import BasketballTeam, BasketballLeague, BasketballPlayer

import logging

from sport.views.general_views import *


def basketball_teams(request):
    teams = BasketballTeam.objects.all()

    context = {
        'teams': teams
    }
    return render(request, 'sport/basketball/basketball_teams.html', context)


def basketball_team_detail_view(request, team_id):
    news = News.objects.all().order_by('-publish_date')

    team = get_object_or_404(BasketballTeam, pk=team_id)
    team_in_games = team.basketballteaminbasketballgame_set.all().order_by('team_score')

    games = []
    for tg in team_in_games:
        games.append(tg.game)
    related_news = get_related_news_by_all_criteria(news, team.name)

    if request.POST:
        if request.POST["part"] == 'filter_news':
            if request.POST['choice'] == 'tag':
                related_news = get_related_news_by_tag(news, team.name)
            elif request.POST['choice'] == 'title':
                related_news = get_related_news_by_title(news, team.name)
            else:
                related_news = get_related_news_by_text(news, team.name)
        elif request.POST["part"] == 'winning_losing':
            games = filter_games_by_winning_loosing(team_in_games, request.POST["choice"])
        elif request.POST["part"] == 'opponent_team':
            games = filter_games_by_opponent_basketball(games, team=team, text=request.POST["opponent_team"])
        elif request.POST['part'] == 'follow':
            team.followers.add(request.user)
            logger = logging.getLogger(__name__)
            logger.info('با موفقیت از این تیم پیروی شد!')

    context = {
        'team': team,
        'related_news': related_news,
        'games': games
    }

    return render(request, 'sport/basketball/basketball_team_detail.html', context)


def basketball_player_detail_view(request, player_id):
    news = News.objects.all().order_by('-publish_date')
    player = get_object_or_404(BasketballPlayer, pk=player_id)
    related_news = get_related_news_by_all_criteria(news, player.first_name, player.last_name)
    if request.POST and request.POST['part'] == 'for_season':
        # todo
        # مفهوم فصل در فوتبال با علی چک شود
        season = request.POST['season']
        season = int(season)
        x = datetime.datetime(season, 1, 1)
        y = datetime.datetime(season + 1, 1, 1)
        events = player.basketballevent_set.all().filter(exact_time__lte=y).filter(exact_time__gte=x)
    else:
        events = player.basketballevent_set.all()

    details = get_details_basketball(events)

    if request.POST and request.POST['part'] == 'filter_news':
        if request.POST['choice'] == 'tag':
            related_news = get_related_news_by_tag(news, player.first_name, player.last_name)

        elif request.POST['choice'] == 'title':
            related_news = get_related_news_by_title(news, player.first_name, player.last_name)
        else:
            related_news = get_related_news_by_text(news, player.first_name, player.last_name)
    if request.POST and request.POST['part'] == 'follow':
        player.followers.add(request.user)
        logger = logging.getLogger(__name__)
        logger.info('با موفقیت از این بازیکن پیروی شد!')
    context = {
        'player': player,
        'related_news': related_news,
        'details': details

    }
    # context.update(details)

    return render(request, 'sport/basketball/basketball_player_detail.html', context)


def basketball_game_detail_view(request, game_id):
    game = get_object_or_404(BasketballGame, pk=game_id)
    teams = game.basketballteaminbasketballgame_set.all()
    team = teams[0].team
    events = get_events_by_game_and_team_basketball(game, team)
    first_team_details = get_details_basketball(events)

    team = teams[1].team

    events = get_events_by_game_and_team_basketball(game, team)
    second_team_details = get_details_basketball(events)

    news = News.objects.all().filter(publish_date__lt=game.date).order_by('-publish_date')
    news_before = get_related_news_to_game(news, teams[0].team.name, teams[1].team.name)

    news = News.objects.all().filter(publish_date__gte=game.date).order_by('-publish_date')
    news_after = get_related_news_to_game(news, teams[0].team.name, teams[1].team.name)

    first_team_players_in_game = []
    second_team_players_in_game = []
    for pg in game.basketballplayerinbasketballgame_set.all():
        if pg.player.team == teams[0].team:
            first_team_players_in_game.append(pg)
        else:
            second_team_players_in_game.append(pg)

    context = {
        'game': game,
        'first_team_details': first_team_details,
        'second_team_details': second_team_details,
        'teams': teams,
        'news_before': news_before,
        'news_after': news_after,
        'first_team_players_in_game': first_team_players_in_game,
        'second_team_players_in_game': second_team_players_in_game

    }
    return render(request, 'sport/basketball/basketball_game_detail.html', context)


def basketball_leagues(request):
    current_year = timezone.now().year
    current_year = int(current_year)

    current_leagues = BasketballLeague.objects.filter(year__gte=current_year)
    archive_leagues = BasketballLeague.objects.filter(year__lt=current_year).order_by('-year')

    if request.POST:
        current_leagues = filter_leagues_by_text(current_leagues, request.POST["part_of_league"])
        archive_leagues = filter_leagues_by_text(archive_leagues, request.POST['part_of_league'])

    context = {
        'current_leagues': current_leagues,
        'archive_leagues': archive_leagues
    }
    return render(request, 'sport/basketball/basketball_leagues.html', context)


def basketball_league_detail(request, league_id):
    league = get_object_or_404(BasketballLeague, pk=league_id)

    try:
        teams_score_card = get_score_card_of_league_basketball(league)
    except:
        teams_score_card = []

    # for weeks:
    try :
        games_separated_by_weeks = separate_by_week_basketball(league)
    except: games_separated_by_weeks = []
    details_of_games_separated_by_weeks = []
    for gw in games_separated_by_weeks:
        details_of_games_of_current_week = []
        for g in gw:
            details = get_details_of_game_basketball(g)
            details_of_games_of_current_week.append(details)
        details_of_games_separated_by_weeks.append(details_of_games_of_current_week)

    context = {
        'league': league,
        'details_of_games_separated_by_weeks': details_of_games_separated_by_weeks,
        'teams_score_card': teams_score_card
    }
    return render(request, 'sport/basketball/basketball_league_deatail.html', context)


# -------------------------------------------------------------------------------------
BASKETBALL_PLAYER_EVENT_CHOICES = (
    ('2PT', 'پرتاب دو امتیازی'),
    ('3PT', 'پرتاب سه امتیازی'),
    ('E', 'خطا'),
    ('R', 'ریباند'),
    ('P', 'پنالتی'),
    ('LP', 'از دست دادن پنالتی'),
    ('CH', 'تعویض'),
)


def get_details_basketball(events):
    total_2PT = 0
    total_3PT = 0
    total_E = 0
    total_R = 0
    total_P = 0
    total_LP = 0
    total_CH = 0

    for e in events:
        if e.event_type == '2PT':
            total_2PT += 1
        elif e.event_type == '3PT':
            total_3PT += 1
        elif e.event_type == 'E':
            total_E += 1
        elif e.event_type == 'R':
            total_R += 1
        elif e.event_type == 'P':
            total_P += 1
        elif e.event_type == 'LP':
            total_LP += 1
        elif e.event_type == 'CH':
            total_CH += 1

    return {'total_2PT': total_2PT,
            'total_3PT': total_3PT,
            'total_E': total_E,
            'total_R': total_R,
            'total_P': total_P,
            'total_LP': total_LP,
            'total_CH': total_CH,
            }


def get_details_of_game_basketball(game):
    teams = game.basketballteaminbasketballgame_set.all()
    team = teams[0].team
    events = get_events_by_game_and_team_basketball(game, team)
    first_team_details = get_details_basketball(events)

    team = teams[1].team

    events = get_events_by_game_and_team_basketball(game, team)
    second_team_details = get_details_basketball(events)

    details = {
        'game': game,
        'teams': teams,
        'first_team_details': first_team_details,
        'second_team_details': second_team_details
    }
    return details


def filter_games_by_opponent_basketball(games, team, text):
    filtered_games = []
    for g in games:
        teams_in_game = g.basketballteaminbasketballgame_set.all()
        if teams_in_game[0].team == team:
            opponent_name = teams_in_game[1].team.name

        else:
            opponent_name = teams_in_game[0].team.name

        if opponent_name.__contains__(text):
            filtered_games.append(g)

    return filtered_games


def separate_by_week_basketball(league):
    games = league.basketballgame_set.order_by('-date')
    if not games:
        return []
    last_game_date = games[0].date
    first_game_date = games.last().date

    # todo change it to persian # done ;))
    last_game_weekday = last_game_date.weekday()
    # last_game_weekday += 2
    # last_game_weekday %= 7

    last_interval = last_game_date - datetime.timedelta(days=last_game_weekday)
    last_week_games = league.basketballgame_set.filter(
        date__gte=last_interval)
    first_game_weekday = first_game_date.weekday()

    # first_game_weekday += 2
    # first_game_weekday %= 7

    first_interval = first_game_date + datetime.timedelta(days=7 - first_game_weekday)
    first_week_games = league.basketballgame_set.filter(
        date__lt=first_interval)

    games_by_weeks = [first_week_games]
    if last_game_date - last_game_date >= datetime.timedelta(days=7):
        date = first_interval
        while date < last_interval:

sport/templates/sport/basketball/basketball_leagues.html
{% extends 'base.html' %}
{% block title %} لیگ ها {% endblock %}


{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>Leagues</title>
        <style>
            h3 {
                color: #2a6496;

            }
        </style>
    </head>
    <body background="/sport/templates/sport/basketball/leagues_bg.jpg">
    {#todo back ground#}
    <br><br>
    <h1>
        لیگ ها
    </h1>
    <br>
    <div class="container">
        <form action="{% url 'sport:basketball_leagues' %}" method="post">
            {% csrf_token %}
            <div class="input-group">


                <input type="text" name="part_of_league" class="form-control"
                       placeholder="لطفا بخشی از نام لیگ را بنویسید">
                <div class="input-group-btn">

                    <button type="submit" class="btn btn-outline-success">جست و جو</button>
                </div>
            </div>
        </form>
    </div>
    <br>
    <div class="container">
        <h3>لیگ های جاری</h3><br>
        {% if current_leagues %}
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>لیگ</th>

                </tr>
                </thead>
                <tbody>


                {% for l in current_leagues %}
                    <tr>
                        <td>
                            <a href="{% url 'sport:league_detail_basketball' l.id %}">{{ l.name }}{{ l.year }}
                                - {{ l.year|add:1 }}</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>هیچ لیگ جاری وجود ندارد! </p>
        {% endif %}
    </div>
    <br>
    <div class="container">
        <h3>لیگ های آرشیو</h3><br>
        {% if archive_leagues %}
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>لیگ</th>

                </tr>
                </thead>
                <tbody>

                {% for l in archive_leagues %}
                    <tr>
                        <td>
                            <a href="{% url 'sport:league_detail_basketball' l.id %}">{{ l.name }} {{ l.year }}
                                - {{ l.year|add:1 }}</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>هیچ لیگ آرشیوی وجود ندارد</p>
        {% endif %}
    </div>
    </body>
{% endblock %}

sport/templates/sport/basketball/basketball_team_detail.html
{% extends 'base.html' %}
{% block title %} جزئیات تیم {% endblock %}

{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>basketball Team Detail</title>


        <style>
            img {
                border-radius: 50%;
            }
            h3 {
                color: #2a6496;

            }
        </style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <script>
            $(document).ready(function () {
                $("#myInput").on("keyup", function () {
                    var value = $(this).val().toLowerCase();
                    $("#myTable tr").filter(function () {
                        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                    });
                });
            });
        </script>

    </head>
    <body>
    <br>
    <br>
    <h1>{{ team.name }}</h1>
    <br>
    <img src="{{ team.basketballimage_set.all.first.image.url }}" class="img-rounded" alt="logo" width="300"
         height="300">


    <br>
    <br>
    <form action="{% url 'sport:basketball-team-detail' team.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="part" value="follow">


        <button type="submit" class="btn btn-outline-danger">دنبال کردن</button>
    </form>

    <br>



    <div class="container">
        <h3>بازیکنان</h3>
        <br>

        {% if team.basketballplayer_set.all %}

            <input class="form-control" id="myInput" type="text" placeholder="بخشی از نام بازیکن را بنویسید...">
            <br>
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>بازیکنان</th>
                </tr>
                </thead>
                <tbody id="myTable">

                {% for p in team.basketballplayer_set.all %}
                    <tr>
                        <td>
                            <br>
                            <img src="{{ p.image.url }}" alt="image of player can not be loaded" width="80"
                                 height="80">
                            <br><br>
                            <p>
                                <a href="{% url 'sport:basketball-player-detail' p.id %}">
                                    {{ p.first_name }} {{ p.last_name }}
                                </a>
                            </p>
                        </td>


                    </tr>
                {% endfor %}

                </tbody>
            </table>
        {% else %}
            <p>بازیکنی برای این تیم وجود ندارد</p>
        {% endif %}

    </div>

    <br>
    <div class="container">
        <h3>پشتیبانان</h3>
        <br>

        {% if team.basketballnonplayer_set.all %}

            <input class="form-control" id="myInput" type="text" placeholder="بخشی از نام بازیکن را بنویسید...">
            <br>
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>پشتیبانان</th>
                </tr>
                </thead>
                <tbody >

                {% for p in team.basketballnonplayer_set.all %}
                    <tr>
                        <td>
                            <br>
                            <img src="{{ p.image.url }}" alt="image of non player " width="80"
                                 height="80">
                            <br><br>
                            <p>

                                {{ p.first_name }} {{ p.last_name }}

                            </p>
                        </td>


                    </tr>
                {% endfor %}

                </tbody>
            </table>
        {% else %}
            <p>پشتیبانی برای این تیم وجود ندارد</p>
        {% endif %}

    </div>
    <br>


    <h3 >بازی ها</h3>
    <hr style="border-style: dashed; color: #00b3ee;">
    <div class="container">
        <form action="{% url 'sport:basketball-team-detail' team.id %}" method="post">
            {% csrf_token %}
            <div class="form-check">
                <input type="hidden" name="part" value="winning_losing">
                <button type="submit" class="btn btn-outline-info">بازیابی بازی ها براساس برد، باخت و مساوی</button>
                <input type="radio" name="choice" value="AW" id="choice 11">
                <label for="choice 11">برد</label>

                <input type="radio" name="choice" value="CL" id="choice 12">
                <label for="choice 12">باخت</label>

                <input type="radio" name="choice" value="BE" id="choice 13">
                <label for="choice 13">مساوی</label>


            </div>
        </form>
    </div>
    <hr style="border-style: dashed; color: #00b3ee;">
    <div class="container">
        <form action="{% url 'sport:basketball-team-detail' team.id %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <input type="hidden" name="part" value="opponent_team">


                <input type="text" name="opponent_team" class="form-control"
                       placeholder="لطفا بخشی از نام حریف را بنویسید">
                <div class="input-group-btn">

                    <button type="submit" class="btn btn-outline-success">جست و جوی تیم براساس نام حریف</button>
                </div>
            </div>
        </form>
    </div>

    <hr style="border-style: dashed; color: #00b3ee;">
    <br>
    <div class="container">
        {% if games %}

            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>تاریخ بازی</th>
                    <th>نام تیم اول</th>
                    <th>امتیاز تیم اول</th>
                    <th>درصد مالکیت تیم اول</th>
                    <th>نام تیم دوم</th>
                    <th>امتیاز تیم دوم</th>
                    <th>درصد مالکیت تیم دوم</th>
                </tr>
                </thead>
                <tbody>

                {% for g in games %}
                    <tr>
                        <td>
                            <a href="{% url 'sport:basketball-game-detail' g.id %}">
                                {{ g.date }}
                            </a>
                        </td>
                        {% for tg in g.basketballteaminbasketballgame_set.all %}
                            <td>
                                {% if  tg.team.name %}
                                    {{ tg.team.name }}
                                {% else %} ??
                                {% endif %}
                            </td>
                            <td>
                                {% if  tg.team_score_Q1 and tg.team_score_Q2 and tg.team_score_Q3 and tg.team_score_Q4 %}
                                    {{ tg.team_score_Q1|add: tg.team_score_Q2|add: tg.team_score_Q3|add:tg.team_score_Q4 }}
                                {% else %} ??
                                {% endif %}
                            </td>
                            <td>
                                {% if  tg.property_percent %}
                                    {{ tg.property_percent }}
                                {% else %} ??
                                {% endif %}
                            </td>

                        {% endfor %}

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>بازی برای این تیم وجود ندارد</p>
        {% endif %}

    </div>

    <br>
    <h3 >اخبار مرتبط</h3>
    <hr style="border-style: dashed; color: #00b3ee;">
    <div class="container">
        <form action="{% url 'sport:basketball-team-detail' team.id %}" method="post">
            {% csrf_token %}
            <div class="form-check">
                <input type="hidden" name="part" value="filter_news">
                <button type="submit" class="btn btn-outline-info">بازیابی اخبار</button>
                <input type="radio" name="choice" value="tag" id="choice 1">
                <label for="choice 1">براساس تگ</label>

                <input type="radio" name="choice" value="title" id="choice 2">
                <label for="choice 2">براساس عنوان</label>

                <input type="radio" name="choice" value="text" id="choice 3">
                <label for="choice 3">براساس متن</label>


            </div>
        </form>
    </div>
    <hr style="border-style: dashed; color: #00b3ee;">
    {% if related_news %}
        <div class="pre-scrollable">

            {% for n in related_news %}
                <div style="display: block">


                    <a href="{% url 'sport:news-detail' n.id %}" type="button"
                            class="btn btn-outline-secondary">{{ n.publish_date }} : {{ n.title }}</a>
                    <br>
                    <br>

                </div>
            {% endfor %}
        </div>
    {% else %}
        <p style="color: darkred">اخباری مرتبط با این بازیکن وجود ندارد!</p>
    {% endif %}
    </body>
{% endblock %}

sport/templates/sport/basketball/basketball_teams.html
{% extends 'base.html' %}
{% block title %} تیم ها {% endblock %}

{% block content %}
    <head>
        <title>Teams</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <style>
            img {
                border-radius: 50%;
            }
            a {
                color: #002a80;
            }
        </style>
    </head>
    <body>

    <div class="container">
    <br><br>
        <h2>تیم ها</h2>
    <br>
        <p> تیم هایی که می توانید اخبار آن ها را از این سایت پیروی کنید:</p>
        <input class="form-control" id="myInput" type="text" placeholder="بخشی از نام تیم را بنویسید">
        <br>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>تیم ها</th>
            </tr>
            </thead>
            <tbody id="myTable">
            {% for t in teams %}
                <tr>
                    <td>

                        <a href="{% url 'sport:basketball-team-detail' t.id %}">
                            {{ t.name }}
                        </a>
                        <img src="{{ t.basketballimage_set.all.first.image.url }}" alt="logo" width="30" height="30">

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>


    </div>

    <script>
        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

    </body>
{% endblock %}