leads/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('api/lead/', views.LeadListCreate.as_view()),
    path('api/news/', views.NewsCreate.as_view()),
    path('test/image', views.test_image)

]

react_django/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('leads.urls')),
                  path('', include('sport.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

sport/urls.py
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.urls import path, include

from react_django import settings
from sport.views import *
from . import views

app_name = "sport"
urlpatterns = [
    # general

    path('', recent_general_news_games, name='home'),
    path('<int:news_id>/news-detail', news_detail_view, name='news-detail'),

    path('accounts/', include('django.contrib.auth.urls')),  # new
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('reset/', reset_request, name='password_reset'),
    path('<str:hashcode>/reset/', reset, name='password_reset_confirm'),
    path('<str:hashcode>/activate/', activate, name='activate'),

    # football

    path('football/teams', football_teams, name='football_teams'),
    path('<int:team_id>/football/team-detail', football_team_detail_view, name='football-team-detail'),
    path('<int:player_id>/football/player-detail', football_player_detail_view, name='football-player-detail'),
    path('<int:game_id>/football/game-detail', football_game_detail_view, name='football-game-detail'),
    path('football/leagues', football_leagues, name='football_leagues'),
    path('<int:league_id>/football/league_detail', football_league_detail, name='league_detail_football'),

    # basketball

    path('basketball/teams', basketball_teams, name='basketball_teams'),
    path('<int:team_id>/basketball/team-detail', basketball_team_detail_view, name='basketball-team-detail'),
    path('<int:player_id>/basketball/player-detail', basketball_player_detail_view, name='basketball-player-detail'),
    path('<int:game_id>/basketball/game-detail', basketball_game_detail_view, name='basketball-game-detail'),
    path('basketball/leagues', basketball_leagues, name='basketball_leagues'),
    path('<int:league_id>/basketball/league_detail', basketball_league_detail, name='league_detail_basketball'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sport/models/general_models.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

TYPE_CHOICES = (
    ('F', 'فوتبال'),
    ('B', 'بسکتبال')
)


class News(models.Model):
    type = models.CharField(max_length=1, choices=TYPE_CHOICES, default='F', verbose_name=_('نوع'))
    title = models.CharField(max_length=100, verbose_name=_('عنوان'))
    text = models.TextField(verbose_name=_('متن'))
    publish_date = models.DateField(verbose_name=_('تاریخ انتشار'))

    def __str__(self):
        s = self.title
        return s

    class Meta:
        verbose_name = _('خبر')
        verbose_name_plural = _('اخبار')
        # verbose_name_plural = "Pieces of news"


# tags and resources and related teams and related players were handled by many to many relationship

#     todo : images of non News

# recent news needed! during last 10/2 days


class Resource(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('نام'))
    news = models.ManyToManyField(News, verbose_name=_('خبر'))

    def __str__(self):
        s = self.name
        return s

    class Meta:
        verbose_name = _('منبع')
        verbose_name_plural = _('منابع')


#     many resources for many pieces of news!


class Tag(models.Model):
    text = models.CharField(max_length=100, verbose_name=_('متن'))
    news = models.ManyToManyField(News, verbose_name=_('خبر'))

    class Meta:
        verbose_name = _('تگ')
        verbose_name_plural = _('تگ ها')

    def __str__(self):
        s = self.text
        return s


#     many tags for many pieces of news!


class Comment(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('عنوان'))
    text = models.TextField(verbose_name=_('متن'))
    writer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('نویسنده'))
    news = models.ForeignKey(News, on_delete=models.CASCADE, verbose_name=_('خبر'))

    class Meta:
        verbose_name = _('نظر')
        verbose_name_plural = _('نظرات')


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'نام کاربری'}),
                               label='نام کاربری',
                               required=True,
                               disabled=False,
                               help_text='')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'رمز عبور'}),
                               label='رمز عبور',
                               required=True,
                               disabled=False,
                               help_text='')

    class Meta:
        model = User
        fields = ['username', 'password']


class SignupForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'نام کاربری'}),
                               label='نام کاربری',
                               required=True,
                               disabled=False,
                               help_text='')
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'نام'}),
                                 label='نام',
                                 required=True,
                                 disabled=False,
                                 help_text='')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'نام خانوادگی'}),
                                label='نام خانوادگی',
                                required=True,
                                disabled=False,
                                help_text='')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'رمز عبور'}),
                                label='رمز عبور',
                                required=True,
                                disabled=False,
                                help_text='')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'تکرار رمز عبور'}),
                                label='تکرار رمز عبور',
                                required=True,
                                disabled=False,
                                help_text='')
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'ایمیل'}),
                             label='ایمیل',
                             max_length=64,
                             help_text='یک ایمیل معتبر وارد کنید')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email')


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    description = models.TextField()
    # picture = models.ImageField(upload_to='static/profile_pictures', blank=True, null=True)
    # authentication_key = models.CharField(max_length=50)
    session_key = models.CharField(null=True, blank=True, max_length=160)
    authentication_key = models.CharField(null=True, blank=True, max_length=50)

# class FootballPlayerInGame(models.Model):
#     game = models.ForeignKey(Game, on_delete=models.CASCADE)
#     player = models.ForeignKey(Player,)
#


class ForgottenUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    key = models.TextField(max_length=32)


class ActivateUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    key = models.TextField(max_length=32)

sport/views/general_views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
import datetime

from sport.models import News, FootballGame, BasketballGame, Comment
from django.utils import timezone


class NewsDetailView(generic.DetailView):
    template_name = 'sport/general/news_detail.html'
    context_object_name = 'news'
    model = News


def news_detail_view(request, news_id):
    news = get_object_or_404(News, pk=news_id)

    if request.POST:
        title = request.POST['title']
        text = request.POST['comment']
        writer = request.user
        new_comment = Comment(title=title, text=text, writer=writer, news=news)
        new_comment.save()

    related_news = []
    related_tags = news.tag_set.all()
    for t in related_tags:
        for n in t.news.all():
            related_news.append(n)
    if related_news.__contains__(news):
        related_news.remove(news)
    comments = news.comment_set.all()

    return render(request, 'sport/general/news_detail.html', {
        'news': news,
        'related_news': related_news,
        "comments": comments

    }
                  )


def recent_general_news_games(request):
    football_news = News.objects.filter(type__exact='F').filter(publish_date__lte=timezone.now()).filter(
        publish_date__gte=timezone.now() - datetime.timedelta(days=2)).order_by('-publish_date')

    basketball_news = News.objects.filter(type__exact='B').filter(publish_date__lte=timezone.now()).filter(
        publish_date__gte=timezone.now() - datetime.timedelta(days=2)).order_by('-publish_date')

    football_teams = request.user.footballteam_set.all()  # for debug
    basketball_teams = request.user.basketballteam_set.all()

    f1_ = request.user.footballteam_set.all()
    f2_ = request.user.footballplayer_set.all()
    f3_ = request.user.basketballteam_set.all()
    f4_ = request.user.basketballplayer_set.all()
    f1 = map(lambda x: x.name, f1_)
    f2 = map(lambda x: str(x), f2_)
    f3 = map(lambda x: str(x), f3_)
    f4 = map(lambda x: str(x), f4_)
    favorites = []
    favorites.extend(f1)
    favorites.extend(f2)
    favorites.extend(f3)
    favorites.extend(f4)

    # games:
    future_football_games = FootballGame.objects.filter(date__gt=timezone.now()).order_by('-date')[:10]
    future_basketball_games = BasketballGame.objects.filter(date__gt=timezone.now()).order_by('-date')[:10]

    football_games = FootballGame.objects.filter(date__lte=timezone.now()).order_by('-date')[:10]
    basketball_games = BasketballGame.objects.filter(date__lte=timezone.now()).order_by('-date')[:10]

    favorite_football_games = FootballGame.objects.filter(
        date__gt=timezone.now() - datetime.timedelta(days=1)).filter(
        date__lte=timezone.now() + datetime.timedelta(days=1)).order_by('-date')[:10]

    favorite_basketball_games = BasketballGame.objects.filter(
        date__gt=timezone.now() - datetime.timedelta(days=1)).filter(
        date__lte=timezone.now() + datetime.timedelta(days=1)).order_by('-date')[:10]

    # news
    favorite_football_news = get_related_news_by_all_criteria(football_news, *favorites)
    favorite_basketball_news = get_related_news_by_all_criteria(basketball_news, *favorites)

    if request.POST:
        n = int(request.POST['number'])
        recent_football_news = News.objects.filter(type__exact='F').filter(publish_date__lte=timezone.now()).order_by(
            '-publish_date')[:n]
        recent_basketball_news = News.objects.filter(type__exact='B').filter(publish_date__lte=timezone.now()).order_by(
            '-publish_date')[:n]

    else:
        recent_football_news = News.objects.filter(type__exact='F').filter(publish_date__lte=timezone.now()).order_by(
            '-publish_date')[:10]
        recent_basketball_news = News.objects.filter(type__exact='B').filter(publish_date__lte=timezone.now()).order_by(
            '-publish_date')[:10]

    context = {
        'recent_football_news': recent_football_news,
        'recent_basketball_news': recent_basketball_news,

        'favorite_football_news': favorite_football_news,
        'favorite_basketball_news': favorite_basketball_news,

        'football_teams': football_teams,
        'basketball_teams': basketball_teams,

        'future_football_games': future_football_games,
        'future_basketball_games': future_basketball_games,

        'football_games': football_games,
        'basketball_games': basketball_games,

        'favorite_football_games': favorite_football_games,
        'favorite_basketball_games': favorite_basketball_games

    }
    return render(request, 'sport/general/general_home_page.html', context)


#  ---------------------------------------------------------------------------------------


def get_related_news_by_all_criteria(news, *special_text):
    related_news = set([])
    for st in special_text:
        for n in news:
            for t in n.tag_set.all():
                if t.text.__contains__(st):
                    related_news.add(n)
            if n.title.__contains__(st):
                related_news.add(n)
            if n.text.__contains__(st):
                related_news.add(n)
    related_news = list(related_news)
    return related_news


def get_related_news_by_tag(news, *special_text):
    related_news = set([])
    for st in special_text:
        for n in news:
            for t in n.tag_set.all():
                if t.text.__contains__(st):
                    related_news.add(n)
    related_news = list(related_news)
    return related_news


def get_related_news_by_title(news, *special_text):
    related_news = set([])
    for st in special_text:
        for n in news:

            if n.title.__contains__(st):
                related_news.add(n)

    related_news = list(related_news)
    return related_news


def get_related_news_by_text(news, *special_text):
    related_news = set([])
    for st in special_text:
        for n in news:
            if n.text.__contains__(st):
                related_news.add(n)
    related_news = list(related_news)
    return related_news




def filter_games_by_winning_loosing(team_in_games, situation_text):
    games = []
    for tg in team_in_games:
        if tg.situation == situation_text:
            games.append(tg.game)
    return games


def get_related_news_to_game(news, *team_names):
    related_news = set([])

    for n in news:
        if n.text.__contains__(team_names[0]) and n.text.__contains__(team_names[1]):
            related_news.add(n)
        if n.title.__contains__(team_names[0]) and n.text.__contains__(team_names[1]):
            related_news.add(n)
    related_news = list(related_news)
    return related_news


def filter_leagues_by_text(leagues, special_text):
    filtered_leagues = []
    for l in leagues:
        league_complete_name = str(l)
        if league_complete_name.__contains__(special_text):
            filtered_leagues.append(l)
    return filtered_leagues

sport/templates/sport/general/news_detail.html
{% extends 'base.html' %}
{% block title %} جزئیات خبر {% endblock %}

{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>News Detail</title>
        <style>
            h3 {
                color: #2a6496;

            }

            img {
                border-radius: 50%;
            }

            #rcorners2 {
                border-radius: 25px;
                border: 2px solid #73AD21;
                padding: 20px;
                width: 200px;
            {#height: 150px;#} background: #c09853;
                display: block;
            }

            .shadow-textarea textarea.form-control::placeholder {
                font-weight: 300;
            }

            .shadow-textarea textarea.form-control {
                padding-left: 0.8rem;
            }
        </style>
    </head>
    <body>
    <div class="container">
        <br><br>
        <h1>{{ news.title }}</h1>
        <p style="color: #006dcc">{{ news.publish_date }}</p>

        {% if news.resource_set.all %}
            <div>
                منابع:

                {% for r in news.resource_set.all %}
                    <div style="display: inline">
                        * {{ r.name }}
                    </div>

                {% endfor %}
                <div style="display: inline">
                    *
                </div>
            </div>

        {% else %}
            <p>منبع ندارد!</p>
        {% endif %}
        <hr style="border-style: dashed; color: #00b3ee;">

        <p>{{ news.text }}</p>

        <hr style="border-style: dashed; color: #00b3ee;">
        {% if news.tag_set.all %}
            <div>
                تگ های مرتبط:

                {% for t in news.tag_set.all %}
                    <div style="display: inline">
                        * {{ t.text }}
                    </div>

                {% endfor %}
                <div style="display: inline">
                    *
                </div>
            </div>

        {% else %}
            <p>تگ مرتبط ندارد!</p>
        {% endif %}
        <hr style="border-style: dashed; color: #00b3ee;">


        <h3>اخبار مرتبط</h3>
        <hr style="border-style: dashed; color: #00b3ee;">
        {% if related_news %}
            <div class="pre-scrollable">

                {% for n in related_news %}
                    <div style="display: block">


                        <a href="{% url 'sport:news-detail' n.id %}" type="button"
                           class="btn btn-outline-secondary">{{ n.publish_date }} : {{ n.title }}</a>
                        <br>
                        <br>

                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p style="color: darkred">اخباری مرتبط با این بازیکن وجود ندارد!</p>
        {% endif %}

        {% if comments %}

            <h3>تصاویر مرتبط با خبر</h3>
            {% if news.basketballimage_set.all or news.footballimage_set.all%}

                {% for i in game.footballimage_set.all %}
                    <img width="600" height="600" src="{{ i.image.url }}" alt="image of game">
                    <br>
                    <p>{{ i.caption }}</p>
                {% endfor %}

                {% for i in game.basketballimage_set.all %}
                    <img width="600" height="600" src="{{ i.image.url }}" alt="image of game">
                    <br>
                    <p>{{ i.caption }}</p>
                {% endfor %}
            {% else %}
                <p>تصویری مرتبط با این خبر وجود ندارد</p>
            {% endif %}
            <hr style="border-style: dashed; color: #00b3ee;">
            <h3>کامنت ها</h3>

            {% for c in comments %}

                <div id="rcorners2">
                    <h5>{{ c.writer.username }}:
                        {{ c.title }}
                    </h5>
                    <p>{{ c.text }}</p>
                </div>
                <br>

            {% endfor %}

        {% else %}
            <p>کامنتی وجود ندارد برای این خبر</p>
        {% endif %}

        <form action="{% url 'sport:news-detail' news.id %}" method="post" id="usrform">
            {% csrf_token %}


            <div class="input-group">

                <input type="text" name="title" class="form-control"
                       placeholder=" موضوع نظر">
                <div class="input-group-btn">

                    <button type="submit" class="btn btn-outline-warning">ارسال نظر</button>
                </div>
            </div>
        </form>
        <br>


        <div class="form-group shadow-textarea">

        <textarea name="comment" form="usrform" class="form-control z-depth-1" id="exampleFormControlTextarea6" rows="3"
                  placeholder="متن نظر خود را وارد کنید..."></textarea>
        </div>
    </div>
    </body>
{% endblock %}