leads/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('api/lead/', views.LeadListCreate.as_view()),
    path('api/news/', views.NewsCreate.as_view()),
    path('test/image', views.test_image)

]

react_django/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('leads.urls')),
                  path('', include('sport.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

sport/urls.py
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.urls import path, include

from react_django import settings
from sport.views import *
from . import views

app_name = "sport"
urlpatterns = [
    # general

    path('', recent_general_news_games, name='home'),
    path('<int:news_id>/news-detail', news_detail_view, name='news-detail'),

    path('accounts/', include('django.contrib.auth.urls')),  # new
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('reset/', reset_request, name='password_reset'),
    path('<str:hashcode>/reset/', reset, name='password_reset_confirm'),
    path('<str:hashcode>/activate/', activate, name='activate'),

    # football

    path('football/teams', football_teams, name='football_teams'),
    path('<int:team_id>/football/team-detail', football_team_detail_view, name='football-team-detail'),
    path('<int:player_id>/football/player-detail', football_player_detail_view, name='football-player-detail'),
    path('<int:game_id>/football/game-detail', football_game_detail_view, name='football-game-detail'),
    path('football/leagues', football_leagues, name='football_leagues'),
    path('<int:league_id>/football/league_detail', football_league_detail, name='league_detail_football'),

    # basketball

    path('basketball/teams', basketball_teams, name='basketball_teams'),
    path('<int:team_id>/basketball/team-detail', basketball_team_detail_view, name='basketball-team-detail'),
    path('<int:player_id>/basketball/player-detail', basketball_player_detail_view, name='basketball-player-detail'),
    path('<int:game_id>/basketball/game-detail', basketball_game_detail_view, name='basketball-game-detail'),
    path('basketball/leagues', basketball_leagues, name='basketball_leagues'),
    path('<int:league_id>/basketball/league_detail', basketball_league_detail, name='league_detail_basketball'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sport/views/basketball_views.py
import pandas as pd

from sport.models import BasketballTeam, BasketballLeague, BasketballPlayer

import logging

from sport.views.general_views import *


def basketball_teams(request):
    teams = BasketballTeam.objects.all()

    context = {
        'teams': teams
    }
    return render(request, 'sport/basketball/basketball_teams.html', context)


def basketball_team_detail_view(request, team_id):
    news = News.objects.all().order_by('-publish_date')

    team = get_object_or_404(BasketballTeam, pk=team_id)
    team_in_games = team.basketballteaminbasketballgame_set.all().order_by('team_score')

    games = []
    for tg in team_in_games:
        games.append(tg.game)
    related_news = get_related_news_by_all_criteria(news, team.name)

    if request.POST:
        if request.POST["part"] == 'filter_news':
            if request.POST['choice'] == 'tag':
                related_news = get_related_news_by_tag(news, team.name)
            elif request.POST['choice'] == 'title':
                related_news = get_related_news_by_title(news, team.name)
            else:
                related_news = get_related_news_by_text(news, team.name)
        elif request.POST["part"] == 'winning_losing':
            games = filter_games_by_winning_loosing(team_in_games, request.POST["choice"])
        elif request.POST["part"] == 'opponent_team':
            games = filter_games_by_opponent_basketball(games, team=team, text=request.POST["opponent_team"])
        elif request.POST['part'] == 'follow':
            team.followers.add(request.user)
            logger = logging.getLogger(__name__)
            logger.info('با موفقیت از این تیم پیروی شد!')

    context = {
        'team': team,
        'related_news': related_news,
        'games': games
    }

    return render(request, 'sport/basketball/basketball_team_detail.html', context)


def basketball_player_detail_view(request, player_id):
    news = News.objects.all().order_by('-publish_date')
    player = get_object_or_404(BasketballPlayer, pk=player_id)
    related_news = get_related_news_by_all_criteria(news, player.first_name, player.last_name)
    if request.POST and request.POST['part'] == 'for_season':
        # todo
        # مفهوم فصل در فوتبال با علی چک شود
        season = request.POST['season']
        season = int(season)
        x = datetime.datetime(season, 1, 1)
        y = datetime.datetime(season + 1, 1, 1)
        events = player.basketballevent_set.all().filter(exact_time__lte=y).filter(exact_time__gte=x)
    else:
        events = player.basketballevent_set.all()

    details = get_details_basketball(events)

    if request.POST and request.POST['part'] == 'filter_news':
        if request.POST['choice'] == 'tag':
            related_news = get_related_news_by_tag(news, player.first_name, player.last_name)

        elif request.POST['choice'] == 'title':
            related_news = get_related_news_by_title(news, player.first_name, player.last_name)
        else:
            related_news = get_related_news_by_text(news, player.first_name, player.last_name)
    if request.POST and request.POST['part'] == 'follow':
        player.followers.add(request.user)
        logger = logging.getLogger(__name__)
        logger.info('با موفقیت از این بازیکن پیروی شد!')
    context = {
        'player': player,
        'related_news': related_news,
        'details': details

    }
    # context.update(details)

    return render(request, 'sport/basketball/basketball_player_detail.html', context)


def basketball_game_detail_view(request, game_id):
    game = get_object_or_404(BasketballGame, pk=game_id)
    teams = game.basketballteaminbasketballgame_set.all()
    team = teams[0].team
    events = get_events_by_game_and_team_basketball(game, team)
    first_team_details = get_details_basketball(events)

    team = teams[1].team

    events = get_events_by_game_and_team_basketball(game, team)
    second_team_details = get_details_basketball(events)

    news = News.objects.all().filter(publish_date__lt=game.date).order_by('-publish_date')
    news_before = get_related_news_to_game(news, teams[0].team.name, teams[1].team.name)

    news = News.objects.all().filter(publish_date__gte=game.date).order_by('-publish_date')
    news_after = get_related_news_to_game(news, teams[0].team.name, teams[1].team.name)

    first_team_players_in_game = []
    second_team_players_in_game = []
    for pg in game.basketballplayerinbasketballgame_set.all():
        if pg.player.team == teams[0].team:
            first_team_players_in_game.append(pg)
        else:
            second_team_players_in_game.append(pg)

    context = {
        'game': game,
        'first_team_details': first_team_details,
        'second_team_details': second_team_details,
        'teams': teams,
        'news_before': news_before,
        'news_after': news_after,
        'first_team_players_in_game': first_team_players_in_game,
        'second_team_players_in_game': second_team_players_in_game

    }
    return render(request, 'sport/basketball/basketball_game_detail.html', context)


def basketball_leagues(request):
    current_year = timezone.now().year
    current_year = int(current_year)

    current_leagues = BasketballLeague.objects.filter(year__gte=current_year)
    archive_leagues = BasketballLeague.objects.filter(year__lt=current_year).order_by('-year')

    if request.POST:
        current_leagues = filter_leagues_by_text(current_leagues, request.POST["part_of_league"])
        archive_leagues = filter_leagues_by_text(archive_leagues, request.POST['part_of_league'])

    context = {
        'current_leagues': current_leagues,
        'archive_leagues': archive_leagues
    }
    return render(request, 'sport/basketball/basketball_leagues.html', context)


def basketball_league_detail(request, league_id):
    league = get_object_or_404(BasketballLeague, pk=league_id)

    try:
        teams_score_card = get_score_card_of_league_basketball(league)
    except:
        teams_score_card = []

    # for weeks:
    try :
        games_separated_by_weeks = separate_by_week_basketball(league)
    except: games_separated_by_weeks = []
    details_of_games_separated_by_weeks = []
    for gw in games_separated_by_weeks:
        details_of_games_of_current_week = []
        for g in gw:
            details = get_details_of_game_basketball(g)
            details_of_games_of_current_week.append(details)
        details_of_games_separated_by_weeks.append(details_of_games_of_current_week)

    context = {
        'league': league,
        'details_of_games_separated_by_weeks': details_of_games_separated_by_weeks,
        'teams_score_card': teams_score_card
    }
    return render(request, 'sport/basketball/basketball_league_deatail.html', context)


# -------------------------------------------------------------------------------------
BASKETBALL_PLAYER_EVENT_CHOICES = (
    ('2PT', 'پرتاب دو امتیازی'),
    ('3PT', 'پرتاب سه امتیازی'),
    ('E', 'خطا'),
    ('R', 'ریباند'),
    ('P', 'پنالتی'),
    ('LP', 'از دست دادن پنالتی'),
    ('CH', 'تعویض'),
)


def get_details_basketball(events):
    total_2PT = 0
    total_3PT = 0
    total_E = 0
    total_R = 0
    total_P = 0
    total_LP = 0
    total_CH = 0

    for e in events:
        if e.event_type == '2PT':
            total_2PT += 1
        elif e.event_type == '3PT':
            total_3PT += 1
        elif e.event_type == 'E':
            total_E += 1
        elif e.event_type == 'R':
            total_R += 1
        elif e.event_type == 'P':
            total_P += 1
        elif e.event_type == 'LP':
            total_LP += 1
        elif e.event_type == 'CH':
            total_CH += 1

    return {'total_2PT': total_2PT,
            'total_3PT': total_3PT,
            'total_E': total_E,
            'total_R': total_R,
            'total_P': total_P,
            'total_LP': total_LP,
            'total_CH': total_CH,
            }


def get_details_of_game_basketball(game):
    teams = game.basketballteaminbasketballgame_set.all()
    team = teams[0].team
    events = get_events_by_game_and_team_basketball(game, team)
    first_team_details = get_details_basketball(events)

    team = teams[1].team

    events = get_events_by_game_and_team_basketball(game, team)
    second_team_details = get_details_basketball(events)

    details = {
        'game': game,
        'teams': teams,
        'first_team_details': first_team_details,
        'second_team_details': second_team_details
    }
    return details


def filter_games_by_opponent_basketball(games, team, text):
    filtered_games = []
    for g in games:
        teams_in_game = g.basketballteaminbasketballgame_set.all()
        if teams_in_game[0].team == team:
            opponent_name = teams_in_game[1].team.name

        else:
            opponent_name = teams_in_game[0].team.name

        if opponent_name.__contains__(text):
            filtered_games.append(g)

    return filtered_games


def separate_by_week_basketball(league):
    games = league.basketballgame_set.order_by('-date')
    if not games:
        return []
    last_game_date = games[0].date
    first_game_date = games.last().date

    # todo change it to persian # done ;))
    last_game_weekday = last_game_date.weekday()
    # last_game_weekday += 2
    # last_game_weekday %= 7

    last_interval = last_game_date - datetime.timedelta(days=last_game_weekday)
    last_week_games = league.basketballgame_set.filter(
        date__gte=last_interval)
    first_game_weekday = first_game_date.weekday()

    # first_game_weekday += 2
    # first_game_weekday %= 7

    first_interval = first_game_date + datetime.timedelta(days=7 - first_game_weekday)
    first_week_games = league.basketballgame_set.filter(
        date__lt=first_interval)

    games_by_weeks = [first_week_games]
    if last_game_date - last_game_date >= datetime.timedelta(days=7):
        date = first_interval
        while date < last_interval:

sport/views/user_views.py
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
import django.contrib.auth as dj_auth

from api.email import send_email
from api.user import generate_hash, request_activation, activation_check, forgotten_check, request_forgotten
from react_django import settings
from sport.models import UserProfile, ForgottenUser
from sport.models import SignupForm
from sport.models import LoginForm


def signup(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    elif request.method == "POST":
        f = SignupForm(request.POST)
        if f.is_valid():
            f.save()
            username = f.cleaned_data['username']
            email = f.cleaned_data['email']
            User.objects.filter(username=username).update(is_active=False)
            new_user = User.objects.get(username=username)
            prof = UserProfile(user=new_user)

            key = request_activation(username)

            send_email(email, 'activation', 'http://127.0.0.1:8000/' + key + '/activate/')

            prof.save()
            return HttpResponseRedirect('/')
    else:
        f = SignupForm()
    return render(request, 'registration/signup.html', {'form': f})


def login(request):
    if request.user.is_authenticated:
        dj_auth.logout(request)
        return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)
        # return HttpResponse("cici")
    elif request.method == "POST":
        f = LoginForm(data=request.POST)
        if f.is_valid():
            username = f.cleaned_data.get('username')
            password = f.cleaned_data.get('password')
            user = dj_auth.authenticate(username=username, password=password)
            if user is not None:
                dj_auth.login(request, user)
                return HttpResponseRedirect(settings.REDIRECT_URL)
                # return HttpResponse("hihi")
    else:
        f = LoginForm()
    return render(request, 'registration/login.html', {'form': f})
    # return HttpResponse("bibi")


def reset_request(request):
    if request.user.is_authenticated:
        dj_auth.logout(request)
        return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)
    elif request.method == "POST":
        email = request.POST.get('email', '')
        if email:
            try:
                username = User.objects.filter(email=email)[0].username

                key = request_forgotten(username)
                send_email(email, 'forgotten', 'http://127.0.0.1:8000/' + key + '/reset/')

                return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
            except IndexError:
                pass

    return render(request, 'registration/reset.html', {})


def activate(request, hashcode):
    if request.user.is_authenticated:
        dj_auth.logout(request)
        return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)

    activation_check(hashcode)
    return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)


def reset(request, hashcode):
    if request.user.is_authenticated:
        dj_auth.logout(request)
        return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)

    username = forgotten_check(hashcode)
    if username:
        if request.method == "POST":
            p1 = request.POST.get('password', '')
            p2 = request.POST.get('password_r', '')
            if p1 and p2 and p1 == p2:
                user = User.objects.filter(username=username)[0]
                user.set_password(p1)
                user.save()
                ForgottenUser.objects.filter(key=hashcode)[0].delete()
                return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
    else:
        return HttpResponseRedirect(settings.REDIRECT_URL)

    return render(request, 'registration/change.html', {})

sport/templates/base.html
<!doctype html>
<html lang="en" dir="rtl">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {#{% load static %}#}
    {#    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.rtl.css' %}">#}
    {#    <link rel="stylesheet" href="{% static 'bootstrap-rtl-master/css/bootstrap-rtl.min.css' %}">#}
    {#    <link rel="stylesheet" href="{% static 'bootstrap-rtl-master/css/bootstrap-responsive-rtl.min.css' %}">#}
    <style>
        body {
            direction: rtl;
            font-family: "B Nazanin";
            text-align: center;
            background-color: #bfbfbf;
        {% load static %}
            {#background: url("{% static 'images/background.png' %}") center;#}
            min-height: 100vh;
        }
    </style>
    <script src="{% static 'js/persian-date.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        function getDate(date) {
            var temp = new Date();
            var day = new Date(date - temp.getTimezoneOffset() * 1000 * 60);
            return new persianDate(day).format('dddd DD MMMM YYYY ساعت HH:mm:ss');
        }
    </script>
    <title>{% block title %}Najimi - Jamshidpor{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">ورزش با ما!</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">خانه<span class="sr-only">(current)</span></a>
            </li>
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sport:login' %}">ورود</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sport:signup' %}">ثبت نام</a>
                </li>
            {% else %}


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        لیگ ها
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'sport:football_leagues' %}">لیگ فوتبال</a>
                        <a class="dropdown-item" href="{% url 'sport:basketball_leagues' %}">لیگ بسکتبال</a>

                    </div>


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        تیم ها
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'sport:football_teams' %}">تیم های فوتبال</a>
                        <a class="dropdown-item" href="{% url 'sport:basketball_teams' %}">تیم های بسکتبال</a>

                    </div>
                </li>

            {% endif %}
            {#            <li class="nav-item dropdown">#}
            {#                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"#}
            {#                   aria-haspopup="true" aria-expanded="false">#}
            {#                    Dropdown#}
            {#                </a>#}
            {#                <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
            {#                    <a class="dropdown-item" href="#">Action</a>#}
            {#                    <a class="dropdown-item" href="#">Another action</a>#}
            {#                    <div class="dropdown-divider"></div>#}
            {#                    <a class="dropdown-item" href="#">Something else here</a>#}
            {#                </div>#}
            {#            </li>#}
            {#            <li class="nav-item">#}
            {#                <a class="nav-link disabled" href="#">Disabled</a>#}
            {#            </li>#}
        </ul>


        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'sport:login' %}">خروج</a>
            </li>
        {% endif %}
    </div>
</nav>

{% block content %}
{% endblock %}
{% block content_ %}
{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.13/js/dataTables.bootstrap4.min.js"></script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var elements = document.getElementsByTagName("INPUT");
        for (var i = 0; i < elements.length; i++) {
            elements[i].oninvalid = function (e) {
                e.target.setCustomValidity("");
                if (!e.target.validity.valid) {
                    e.target.setCustomValidity("این ورودی نمی‌تواند خالی باشد");
                }
            };
            elements[i].oninput = function (e) {
                e.target.setCustomValidity("");
            };
        }
    })
</script>
</body>
</html>